package com.coconutsrule.otoutlets.outletsapi.security;

public enum Permission {
    BUILDING_CREATE,
    BUILDING_UPDATE,
    BUILDING_RETREIVE,
    BUILDING_DELETE,
    BUILDING_FLOOR_CREATE,
    BUILDING_FLOOR_UPDATE,
    BUILDING_FLOOR_RETREIVE,
    BUILDING_FLOOR_DELETE,
    ITEM_CREATE,
    ITEM_UPDATE,
    ITEM_RETREIVE,
    ITEM_DELETE,
    PLACE_CREATE,
    PLACE_UPDATE,
    PLACE_RETREIVE,
    PLACE_DELETE,
    USER_CREATE,
    USER_UPDATE,
    USER_RETREIVE,
    USER_DELETE
}
